name: Deploy to Test

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["Security Scan"]
    types:
      - completed

jobs:
  deploy-test:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0
        
    - name: Terraform Init
      working-directory: ./terraform/test
      run: terraform init
      
    - name: Terraform Plan
      working-directory: ./terraform/test
      run: terraform plan -var="allowed_ip=${{ secrets.USER_PUBLIC_IP }}"
      
    - name: Terraform Apply
      working-directory: ./terraform/test
      run: terraform apply -auto-approve -var="allowed_ip=${{ secrets.USER_PUBLIC_IP }}" -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"
