name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      approval:
        description: 'Confirm production deployment'
        required: true
        type: boolean

jobs:
  deploy-prod:
    if: ${{ github.event.inputs.approval == 'true' }}
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0
        
    - name: Terraform Init
      working-directory: ./terraform/prod
      run: terraform init
      
    - name: Terraform Plan
      working-directory: ./terraform/prod
      run: terraform plan -var="allowed_ip=${{ secrets.USER_PUBLIC_IP }}"
      
    - name: Terraform Apply
      working-directory: ./terraform/prod
      run: terraform apply -auto-approve -var="allowed_ip=${{ secrets.USER_PUBLIC_IP }}"
